// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFI_RU_ngv2-s2SF4Sg5RWgHYyzfHxoVM',
    appId: '1:735450560826:android:0b6dad4a92672384567803',
    messagingSenderId: '735450560826',
    projectId: 'tripsuite-app',
    storageBucket: 'tripsuite-app.firebasestorage.app',
  );

  // TODO: Update the iOS appId with the actual iOS app ID from Firebase Console
  // To get the iOS app ID:
  // 1. Go to Firebase Console > Project Settings
  // 2. Add an iOS app if not already added (bundle ID: com.example.tripsuiteAppBoilerplate)
  // 3. Download GoogleService-Info.plist and find the app ID, or copy it from the Firebase Console
  // 4. Replace 'YOUR_IOS_APP_ID' below with the actual iOS app ID (format: 1:735450560826:ios:XXXXXXXX)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFI_RU_ngv2-s2SF4Sg5RWgHYyzfHxoVM',
    appId:
        '1:735450560826:ios:YOUR_IOS_APP_ID', // Update this with your iOS app ID from Firebase Console
    messagingSenderId: '735450560826',
    projectId: 'tripsuite-app',
    storageBucket: 'tripsuite-app.firebasestorage.app',
    iosBundleId: 'com.example.tripsuiteAppBoilerplate',
  );
}

